services:

  poc-postgres:

    container_name: poc-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: organisation
    volumes:
      - poc-postgres-data:/var/lib/postgresql/data

  poc-adminer:

    container_name: poc-adminer
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: organisation
    depends_on:
      - poc-postgres

  poc-rabbitmq:

    container_name: poc-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - poc-rabbitmq-data:/var/lib/rabbitmq
      
volumes:
  poc-postgres-data:
  poc-rabbitmq-data: