services:

  poc-postgres:

    container_name: poc-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: organisation
    volumes:
      - poc-postgres-data:/var/lib/postgresql/data

  poc-adminer:

    container_name: poc-adminer
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: organisation
    depends_on:
      - poc-postgres

  poc-rabbitmq:

    container_name: poc-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - poc-rabbitmq-data:/var/lib/rabbitmq

  poc-mongodb:

    container_name: poc-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - poc-mongodb-data:/data/db
  
  poc-mongo-express:

    container_name: poc-mongo-express
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: poc-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - poc-mongodb

volumes:
  poc-postgres-data:
  poc-rabbitmq-data:
  poc-mongodb-data: